SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS vets;
DROP TABLE IF EXISTS pet_owners;
DROP TABLE IF EXISTS clinics;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE clinics (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  city VARCHAR(120) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE vets (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  clinic_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(160) NOT NULL,
  specialty VARCHAR(160) NULL,
  KEY idx_vet_clinic (clinic_id),
  CONSTRAINT fk_vet_clinic FOREIGN KEY (clinic_id)
    REFERENCES clinics(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pet_owners (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(160) NOT NULL,
  phone VARCHAR(60) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pets (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  owner_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  species VARCHAR(120) NOT NULL,
  KEY idx_pet_owner (owner_id),
  CONSTRAINT fk_pet_owner FOREIGN KEY (owner_id)
    REFERENCES pet_owners(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE appointments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  clinic_id BIGINT UNSIGNED NOT NULL,
  vet_id    BIGINT UNSIGNED NOT NULL,
  pet_id    BIGINT UNSIGNED NOT NULL,
  scheduled_for DATETIME NOT NULL,
  status ENUM('new','confirmed','done','canceled') NOT NULL DEFAULT 'new',
  KEY idx_app_clinic (clinic_id),
  KEY idx_app_vet    (vet_id),
  KEY idx_app_pet    (pet_id),
  CONSTRAINT fk_app_clinic FOREIGN KEY (clinic_id)
    REFERENCES clinics(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_app_vet FOREIGN KEY (vet_id)
    REFERENCES vets(id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_app_pet FOREIGN KEY (pet_id)
    REFERENCES pets(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
